-- PostgreSQL Full-Text Search Optimization (Trigram Index)
-- This migration adds GIN indexes to the "Product" table to accelerate the ILIKE queries generated by Prisma's `contains: query` filter.
-- It avoids sequential table scans during product lookups.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS "idx_product_name_trgm" ON "Product" USING GIN ("name" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "idx_product_desc_trgm" ON "Product" USING GIN ("description" gin_trgm_ops);
